kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "gcJobs.name" . }}
rules:
- apiGroups:
  - tf.isaaguilar.com
  resources:
  - terraforms
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups: ["batch", "extensions"]
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - delete