apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "gcJobs.name" . }}
  labels:
    app: jenkins-x-lighthouse-gcjobs
spec:
  concurrencyPolicy: {{ .Values.gcJobs.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.gcJobs.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: {{ template "gcJobs.name" . }}
            release: {{ .Release.Name }}
{{- if .Values.gcJobs.podAnnotations }}
          annotations:
{{ toYaml .Values.gcJobs.podAnnotations | indent 12 }}
{{- end }}
        spec:
          containers:
            - command:
              - jx-test
              - gc
              - -d
              - {{ .Values.duration }}
              - --app-certificate-file
              - /secret/private-key.pem
              - --app-id
              - {{ .Values.appID | int64 | quote }}
              env:
              - name: XDG_CONFIG_HOME
                value: /home
              image: {{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag . }}
              imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
              name: {{ template "gcJobs.name" . }}
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /secret
                  name: bdd-app
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: {{ template "gcJobs.name" . }}
          volumes:
          - name: bdd-app
            secret:
              secretName: bdd-app
  successfulJobsHistoryLimit: {{ .Values.gcJobs.successfulJobsHistoryLimit }}
  schedule: {{ .Values.gcJobs.schedule | quote }}
  startingDeadlineSeconds: 4000
  suspend: false
