apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testruns.jxtest.jenkins.io
spec:
  group: jxtest.jenkins.io
  names:
    kind: TestRun
    singular: testrun
    plural: testruns
    shortNames:
      - tr
  scope: Namespaced
  version: v1alpha1
